---
title: "James, testing"
output:
  pdf_document: default
  html_document: default
date: "2026-01-29"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## R dataset
```{r load}
nyc <- read.csv("nyc.csv")
str(nyc)
```
## Including Plots
```{r plot}
# op <- par(no.readonly = TRUE)
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1))

plot(nyc$Food, nyc$Price,
     xlab = "Food rating (out of 30)", ylab = "Price (USD)",
     main = "Price vs Food", pch = 19)
#abline(lm(Price ~ Food, data = nyc), lty = 2)

plot(nyc$Decor, nyc$Price,
     xlab = "Decor rating (out of 30)", ylab = "Price (USD)",
     main = "Price vs Decor", pch = 19)
#abline(lm(Price ~ Decor, data = nyc), lty = 2)

plot(nyc$Service, nyc$Price,
     xlab = "Service rating (out of 30)", ylab = "Price (USD)",
     main = "Price vs Service", pch = 19)
#abline(lm(Price ~ Service, data = nyc), lty = 2)

# East is binary; jitter helps show overlap
plot(nyc$East, nyc$Price,
     xlab = "East of Fifth Ave (0=No, 1=Yes)", ylab = "Price (USD)",
     main = "Price vs East", pch = 19, xaxt = "n")
axis(1, at = c(0, 1), labels = c("0", "1"))
```
## Fit the regression model and summarize the results
```{r regression}
fit <- lm(Price ~ Food + Decor + Service + East, data = nyc)
print(summary(fit))
print(confint(fit))
```
## Produce residual diagnostic plots, arranging multiple plots within a single figure
```{r figures}
op <- par(no.readonly = TRUE)
par(mfrow = c(2, 2))
plot(fit) # Produces: Residuals vs Fitted, QQ, Scale-Location, Residuals vs Leverage
par(op)
```

